export const getWeapons = () => {
    const weapons = [
        {
            type: "assault",
            name: "ak47",
            rpm: 600,
            range: 550,
            damage: 36,
            magSize: 30,
            reloadTime: 2.0,
            bulletPerShot: 1,
            isBurst: false,
        },
        {
            type: "assault",
            name: "aug",
            rpm: 700,
            range: 600,
            damage: 31,
            magSize: 30,
            reloadTime: 2.1,
            bulletPerShot: 1,
            isBurst: false,
        },
        {
            type: "assault",
            name: "sg550",
            rpm: 650,
            range: 650,
            damage: 33,
            magSize: 30,
            reloadTime: 2.2,
            bulletPerShot: 1,
            isBurst: false,
        },
        {
            type: "assault",
            name: "m4",
            rpm: 750,
            range: 520,
            damage: 29,
            magSize: 30,
            reloadTime: 1.9,
            bulletPerShot: 1,
            isBurst: false,
        },

        {
            type: "smg",
            name: "ump",
            rpm: 550,
            range: 400,
            damage: 34,
            magSize: 25,
            reloadTime: 1.3,
            bulletPerShot: 1,
            isBurst: false,
        },
        {
            type: "smg",
            name: "mac10",
            rpm: 1100,
            range: 350,
            damage: 20,
            magSize: 30,
            reloadTime: 1.0,
            bulletPerShot: 1,
            isBurst: false,
        },
        {
            type: "smg",
            name: "p90",
            rpm: 900,
            range: 450,
            damage: 22,
            magSize: 50,
            reloadTime: 1.2,
            bulletPerShot: 1,
            isBurst: false,
        },
    ];

    return weapons;
};

